services:

  mysql:
    build:
      context: database
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: IMDB
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysql
      FRONTEND_HOST: http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

  browserless-chrome:
    image: browserless/chrome:latest
    platform: linux/amd64
    environment:
      PORT: "4000"
    ports:
      - "4000:4000"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      BACKEND_API: http://backend:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - browserless-chrome