services:

  mysql:
    build:
      context: database
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: IMDB
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - imdb-data:/var/lib/mysql

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysql
    ports:
      - 8080:8080
    depends_on:
      - mysql

volumes:
  imdb-data: