services:

  mysql:
    build:
      context: database
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: IMDB
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - imdb-data:/var/lib/mysql

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysql
      FRONTEND_HOST: http://frontend:5173
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      BACKEND_API: http://backend:8080
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend

volumes:
  imdb-data: