services:

  mysql:
    image: stefanomontr/imdb-mysql:0.0.2
    platform: linux/amd64
    deploy:
      resources:
        limits:
          memory: 6G
    environment:
      MYSQL_DATABASE: IMDB
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  backend:
    image: stefanomontr/imdb-backend:0.0.3
    platform: linux/amd64
    environment:
      MYSQL_HOST: mysql
      FRONTEND_HOST: http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

  browserless-chrome:
    image: browserless/chrome:latest
    platform: linux/amd64
    environment:
      PORT: "4000"
    ports:
      - "4000:4000"

  frontend:
    image: stefanomontr/imdb-frontend:0.0.3
    platform: linux/amd64
    environment:
      BACKEND_API: http://backend:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - browserless-chrome
